-- =====================================================================
-- V6 — Reference data from Drivers Student Manager.xlsx
-- =====================================================================
--  Loads:
--    * 56 SGI mistake categories (uses source_code + points from V5)
--    * 99 SGI training topics
--
--  Runs in EVERY environment (dev, qa, prod) — these are non-PII
--  reference catalogues, not customer data.  Idempotent via the
--  UNIQUE (jurisdiction, source_code) / (jurisdiction, category_name)
--  constraints + ON CONFLICT DO NOTHING.
-- =====================================================================

-- -------------------------------------------------------------------
-- Mistake categories (56 rows) — keyed on source_code 'M001'..'M056'.
-- Safe to re-run; ON CONFLICT DO NOTHING skips duplicates.
-- -------------------------------------------------------------------

INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M001', 'Lanes — Shoulder Check', 'MINOR', 2, 10, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M002', 'Parking — Position', 'MINOR', 2, 20, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M003', 'Signalling — Lane Fail', 'MINOR', 2, 30, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M004', 'Stopping — Crosswalk', 'MINOR', 2, 40, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M005', 'Dangerous — Failed to Anticipate', 'FAIL', 10, 50, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M006', 'Intersections — Hesitate', 'MINOR', 2, 60, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M007', 'Turning — Wide Turn', 'MINOR', 2, 70, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M008', 'Speed — Speeding', 'FAIL', 10, 80, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M009', 'Lanes — Improper Lane', 'MAJOR', 5, 90, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M010', 'Signalling — No Signal', 'MINOR', 2, 100, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M011', 'Observation / Awareness — Hesitate', 'MINOR', 2, 110, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M012', 'Parking — Poor observation', 'MINOR', 2, 120, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M013', 'Observation / Awareness — Unnecessary checking', 'MINOR', 2, 130, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M014', 'Lanes — Went to 2nd/ parking lot', 'MAJOR', 3, 140, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M015', 'Lanes — Unnecessary lane change', 'MINOR', 2, 150, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M016', 'Lanes — Went to Right/Left', 'FAIL', 10, 160, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M017', 'Lanes — Want to go left/Right', 'MAJOR', 5, 170, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M018', 'Lanes — Touch white solid line', 'MINOR', 2, 180, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M019', 'Lanes — Touch yellow solid line', 'MINOR', 2, 190, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M020', 'Lanes — Yellow line touch', 'MINOR', 2, 200, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M021', 'Shoulder Check — Shoulder Check Right', 'MINOR', 2, 210, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M022', 'Shoulder Check — Shoulder Check Left', 'MINOR', 2, 220, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M023', 'Shoulder Check — Without shoulder check (lane change)', 'MAJOR', 5, 230, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M024', 'Signalling — Without signal turn right', 'MAJOR', 5, 240, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M025', 'Signalling — Without signal turn left', 'FAIL', 10, 250, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M026', 'Signalling — Start without signal', 'MINOR', 2, 260, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M027', 'Signalling — Too soon signal', 'MINOR', 2, 270, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M028', 'Signalling — Late signal', 'MINOR', 2, 280, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M029', 'Signalling — Fail to cancel signal', 'MINOR', 2, 290, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M030', 'Signalling — Wrong signalling', 'MINOR', 2, 300, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M031', 'Signalling — Signaling R/L went straight', 'FAIL', 10, 310, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M032', 'Turning — Wide right/left turn', 'MAJOR', 5, 320, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M033', 'Turning — Hit / touches curb', 'MAJOR', 5, 330, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M034', 'Turning — Slow turn', 'MAJOR', 5, 340, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M035', 'Turning — Wrong steering', 'MINOR', 2, 350, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M036', 'Intersections — Hesitant at intersection', 'MINOR', 2, 360, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M037', 'Intersections — Said left/right went straight', 'MINOR', 2, 370, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M038', 'Intersections — Amber light violation', 'FAIL', 10, 380, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M039', 'Intersections — Green light violation', 'FAIL', 10, 390, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M040', 'Intersections — Red light / Stop sign violation', 'FAIL', 10, 400, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M041', 'Right of Way / Yield — Not yield Right/Left', 'MINOR', 2, 410, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M042', 'Right of Way / Yield — Pedestrian (failure to yield)', 'FAIL', 10, 420, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M043', 'Stopping — Block pedestrian crosswalk', 'MAJOR', 5, 430, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M044', 'Stopping — Said STOP (verbal prompt needed)', 'FAIL', 10, 440, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M045', 'Parking — Parallel', 'MAJOR', 5, 450, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M046', 'Parking — Not stop for parking', 'MINOR', 2, 460, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M047', 'Parking — Went to parking lot', 'MINOR', 2, 470, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M048', 'Parking — 2nd attempt', 'MINOR', 2, 480, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M049', 'Speed — Too slow (72 in 90 / 25 in 50)', 'MAJOR', 5, 490, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M050', 'Vehicle Control — Wrong gear', 'MINOR', 2, 500, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M051', 'Parking — Wrong gear / signal', 'MAJOR', 5, 510, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M052', 'Vehicle Control — Touches curb', 'MINOR', 2, 520, FALSE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M053', 'Dangerous — Honk (unnecessary)', 'FAIL', 10, 530, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M054', 'Parking — Parallel alignment', 'MAJOR', 5, 540, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M055', 'Stopping — General position errors', 'MINOR', 2, 550, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;
INSERT INTO mistake_categories (jurisdiction, source_code, category_name, severity, points, display_order, active) VALUES ('SGI', 'M056', 'Parking — Hit the curb', 'MAJOR', 5, 560, TRUE) ON CONFLICT (jurisdiction, category_name) DO UPDATE SET source_code = EXCLUDED.source_code, severity = EXCLUDED.severity, points = EXCLUDED.points, display_order = EXCLUDED.display_order, active = EXCLUDED.active;

-- -------------------------------------------------------------------
-- Training topics (99 rows).  SGI handbook URLs preserved for deep links.
-- -------------------------------------------------------------------

INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0001', 'Introduction', 'Welcome to driving', 'Purpose of the handbook and responsibilities of safe driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/introduction', 10, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0002', 'Licence Program', 'Saskatchewan driver''s licence program', 'Overview of Saskatchewan’s driver licensing system', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/saskatchewan-driver-s-licence-program', 20, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0003', 'Licence Program', 'Driver''s licence', 'Licence classes, requirements, and eligibility criteria', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/driver-s-licence', 30, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0004', 'Licence Program', 'Vehicle registration', 'Rules and requirements for vehicle ownership and registration', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/vehicle-registration', 40, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0005', 'Licence Program', 'Graduated Driver Licensing program', 'Overview of the Graduated Driver Licensing (GDL) system', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/graduated-driver-licensing-program', 50, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0006', 'Licence Program', 'Change of name or address', 'Process for updating legal name or address on driving records', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/change-of-name-or-address', 60, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0007', 'Licence Program', 'Classified licence system', 'Explanation of driver licence classification system', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/classified-licence-system', 70, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0008', 'Licence Program', 'Medical requirements', 'Medical standards required to obtain and maintain a driver’s licence', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/medical-requirements', 80, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0009', 'Licence Program', 'Operating in the United States', 'Requirements and rules for driving in the United States', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/operating-in-the-united-states', 90, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0010', 'Licence Program', 'Mandatory driver education', 'Requirements for mandatory driver education programs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/mandatory-driver-education', 100, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0011', 'Licence Program', 'Preparing for your road test', 'Guidance and preparation tips for the road test', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/preparing-for-your-road-test', 110, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0012', 'Licence Program', 'Before the examination', 'Requirements and expectations before taking driving exams', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/before-the-examination', 120, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0013', 'Licence Program', 'Booking tests', 'Procedures for booking written and road tests', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/your-test', 130, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0014', 'Rules of Road', 'Basic information and rules of the road', 'Fundamental road laws and safe driving responsibilities', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/basic-information-and-rules-of-the-road', 140, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0015', 'Rules of Road', 'Speeding, stunting and racing', 'Laws, penalties, and risks related to speeding and racing', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/speed', 150, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0016', 'Rules of Road', 'Distracted driving', 'Risks, laws, and consequences of distracted driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/distracted-driving', 160, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0017', 'Rules of Road', 'Stopping and parking', 'Rules and safe practices for stopping and parking vehicles', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/stopping-and-parking', 170, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0018', 'Rules of Road', 'Sharing the road', 'Safe practices for interacting with all road users', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/sharing-the-road', 180, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0019', 'Rules of Road', 'The concept of gates', 'Explanation of the “gate” concept used for scanning and awareness', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/the-concept-of-gates', 190, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0020', 'Rules of Road', 'Blind spots', 'Understanding blind spots and how to manage them safely', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/blind-spots', 200, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0021', 'Rules of Road', 'Directional dividing lines', 'Meaning and use of directional dividing lines on roadways', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/directional-dividing-lines', 210, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0022', 'Rules of Road', 'Traffic lanes', 'Rules and structure of traffic lanes', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/traffic-lanes', 220, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0023', 'Rules of Road', 'Lane position', 'Proper lane positioning for safe driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/lane-position', 230, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0024', 'Rules of Road', 'Lane selection', 'Guidelines for choosing the correct lane', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/lane-selection', 240, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0025', 'Rules of Road', 'Signalling', 'Proper use of vehicle signals and communication', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/signalling', 250, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0026', 'Rules of Road', 'Changing lanes', 'Safe procedures for changing lanes', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/changing-lanes', 260, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0027', 'Rules of Road', 'Passing', 'Rules and techniques for passing safely', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/when-passing', 270, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0028', 'Rules of Road', 'Bus lanes and bicycle lanes', 'Rules for sharing and using bus and bicycle lanes', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/bus-lanes-and-bicycle-lanes', 280, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0029', 'Rules of Road', 'Turning', 'Rules and techniques for left and right turns', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/turns', 290, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0030', 'Rules of Road', 'Centre turning lanes', 'Proper use of centre turning lanes', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/centre-turning-lanes', 300, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0031', 'Rules of Road', 'Right-of-way', 'Rules determining who must yield in traffic situations', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/right-of-way', 310, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0032', 'Rules of Road', 'Stopping positions', 'Proper vehicle stopping positions at intersections', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/stopping-positions', 320, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0033', 'Rules of Road', 'Roundabouts', 'Rules and safe navigation of roundabouts', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/roundabouts-and-diverging-diamond-interchange', 330, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0034', 'Rules of Road', 'Highways', 'Highway driving rules and safety practices', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/highways', 340, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0035', 'Rules of Road', 'Pedestrians', 'Responsibilities toward pedestrian safety', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/pedestrians', 350, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0036', 'Rules of Road', 'Crossing urban streets', 'Safe procedures for crossing urban streets', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/crossing-urban-streets', 360, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0037', 'Rules of Road', 'Wheelchairs and mobility aids', 'Safe interaction with mobility aid users', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/wheelchairs-and-mobility-aids', 370, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0038', 'Rules of Road', 'Motorcycles', 'Road sharing rules for motorcycles and other vehicles', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/motorcycles', 380, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0039', 'Rules of Road', 'Medians', 'Purpose and use of road medians', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/medians', 390, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0040', 'Rules of Road', 'Parking lots', 'Rules and restrictions in parking areas', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/parking-lots', 400, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0041', 'Rules of Road', 'Headlights', 'Proper use of headlights for visibility and safety', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/headlights', 410, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0042', 'Rules of Road', 'Night driving and low visibility', 'Safe driving techniques in darkness and poor visibility', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/night-driving-and-low-visibility', 420, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0043', 'Rules of Road', 'Choosing the right speed', 'Guidelines for selecting safe and appropriate speeds', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/choosing-the-right-speed', 430, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0044', 'Rules of Road', 'Rules related to vehicles', 'General compliance rules related to vehicle operation', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/rules-related-to-vehicles', 440, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0045', 'Signs & Signals', 'Traffic signs', 'Overview and classification of traffic signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/traffic-signs', 450, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0046', 'Signs & Signals', 'Six basic sign', 'Understanding six basic traffic sign shapes', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/six-basic-sign-shapes-every-driver-must-know', 460, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0047', 'Signs & Signals', 'Sign colours', 'Meaning of standard traffic sign colours', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/standard-sign-colours', 470, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0048', 'Signs & Signals', 'Regulatory signs', 'Rules conveyed by regulatory traffic signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/regulatory-signs', 480, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0049', 'Signs & Signals', 'Regulatory parking signs', 'Rules indicated by parking regulation signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/regulatory-parking-signs', 490, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0050', 'Signs & Signals', 'Regulatory pedestrian crossing signs', 'Rules for pedestrian crossing signage', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/regulatory-pedestrian-crossing-signs', 500, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0051', 'Signs & Signals', 'Regulatory lane designation signs', 'Lane usage instructions from regulatory signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/regulatory-lane-designation-signs', 510, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0052', 'Signs & Signals', 'Regulatory turn control signs', 'Turn restrictions and instructions from signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/regulatory-turn-control-signs', 520, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0053', 'Signs & Signals', 'Warning signs', 'Meaning and purpose of warning signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/warning-signs', 530, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0054', 'Signs & Signals', 'Construction signs', 'Safety and rules in construction zones', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/construction-signs', 540, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0055', 'Signs & Signals', 'Railway crossings', 'Safety rules at railway crossings', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/railway-crossings', 550, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0056', 'Signs & Signals', 'Crossroad delineators', 'Guidance provided by crossroad delineator signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/crossroad-delineators', 560, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0057', 'Signs & Signals', 'Guide signs', 'Directional and navigational guide signs', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/guide-signs', 570, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0058', 'Signs & Signals', 'Information signs', 'Informational road signs and their meaning', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/information-signs', 580, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0059', 'Signs & Signals', 'Traffic signals', 'Meaning and operation of traffic signals', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/traffic-signals', 590, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0060', 'Basic Driving Skills', 'Hazards and awareness', 'Identifying and responding to road hazards', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/hazards', 600, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0061', 'Basic Driving Skills', 'IPDE method', 'IPDE method: Identify, Predict, Decide, Execute for safe driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/the-ipde-method-of-driving', 610, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0062', 'Basic Driving Skills', 'Time and space', 'Relationship between time, space, and safe reaction', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/time-the-key-to-judgment', 620, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0063', 'Basic Driving Skills', 'Eye use', 'Techniques for scanning and visual awareness', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/eye-use', 630, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0064', 'Basic Driving Skills', 'Before driving', 'Pre-drive inspection and vehicle setup procedures', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/before-you-drive', 640, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0065', 'Basic Driving Skills', 'Steering', 'Proper steering control techniques', 'https://youtu.be/6mm56SYOYR0?si=OFIadFy2SSnQ3-ay', 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/steering', 650, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0066', 'Basic Driving Skills', 'Accelerating', 'Techniques for smooth and controlled acceleration', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/accelerating', 660, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0067', 'Basic Driving Skills', 'Manual transmission', 'Operating vehicles with manual transmission', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/standard-manual-transmission-vehicles', 670, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0068', 'Basic Driving Skills', 'Automatic transmission', 'Operating vehicles with automatic transmission', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/automatic-transmission-vehicles', 680, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0069', 'Basic Driving Skills', 'Low speed skills', 'Techniques for safe control at low speeds', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/low-speed-skills', 690, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0070', 'Advanced Driving', 'Parallel parking', 'Step-by-step parallel parking techniques', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/parking-lots', 700, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0071', 'Advanced Driving', 'Turning', 'Fundamentals of safe vehicle turning', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/turning', 710, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0072', 'Advanced Driving', 'Highway driving', 'Safe practices for highway driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/highway-driving', 720, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0073', 'Advanced Driving', 'Passing', 'Safe passing techniques in advanced driving situations', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/passing', 730, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0074', 'Advanced Driving', 'Curves and corners', 'Safe driving techniques for curves and corners', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/curves-and-corners', 740, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0075', 'Advanced Driving', 'Driving in mountains', 'Driving techniques for mountainous terrain', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/driving-in-mountains', 750, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0076', 'Advanced Driving', 'Grid, municipal and resource access roads', 'Driving on rural, municipal, and resource roads', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/grid-municipal-and-resource-access-roads', 760, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0077', 'Advanced Driving', 'Winter driving', 'Techniques for safe driving on snow and ice', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/winter-driving', 770, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0078', 'Advanced Driving', 'Braking', 'Proper braking techniques for safe stopping', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/braking', 780, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0079', 'Advanced Driving', 'Emergency driving', 'Handling vehicle breakdowns and emergency situations', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/emergency-driving', 790, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0080', 'Advanced Driving', 'Collisions', 'Overview of vehicle collisions and contributing factors', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/understanding-collisions', 800, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0081', 'Advanced Driving', 'What to do if you''re in a collision', 'Steps to take immediately after a collision', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/what-to-do-if-you-are-in-a-collision', 810, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0082', 'Advanced Driving', 'Impairing factors (other than drugs and alcohol)', 'Non-substance factors that can impair driving ability', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/other-impairing-factors', 820, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0085', 'Impairment', 'Alcohol effects', 'How alcohol affects driving ability and safety', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/alcohol', 830, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0086', 'Impairment', 'Drug impairment', 'Effects of drugs on driving performance', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/drugs', 840, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0087', 'Impairment', 'Drinking and drugs combined', 'Combined effects of alcohol and drugs on driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/drinking-and-drugs-combined', 850, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0088', 'Impairment', 'Students Against Drinking and Driving (SADD)', 'Overview of SADD and its role in preventing impaired driving', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/sadd', 860, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0089', 'Law Compliance', 'The Traffic Safety Act', 'Overview of Saskatchewan’s Traffic Safety Act', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/the-traffic-safety-act', 870, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0090', 'Law Compliance', 'The Criminal Code of Canada', 'Overview of criminal driving-related offences in Canada', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/the-criminal-code-of-canada', 880, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0091', 'Law Compliance', 'Traffic tickets', 'Types of traffic violations and penalties', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/traffic-tickets', 890, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0092', 'Law Compliance', 'Driver Improvement Program', 'Overview of driver improvement interventions and requirements', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/driver-improvement-program', 900, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0093', 'Law Compliance', 'Safe Driver Recognition', 'Program recognizing safe driving behaviour and records', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/safe-driver-recognition', 910, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0094', 'Fuel Efficiency', 'Efficient driving habits', 'Driving techniques to improve fuel efficiency', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/fuel-efficient-driving-techniques', 920, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0095', 'Animations', 'Highway driving animations', 'Animated learning content for highway driving concepts', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/highway-driving-animations', 930, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0096', 'Animations', 'Interchanges animations', 'Animated explanations of highway interchanges', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/interchanges-animations', 940, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0097', 'Animations', 'Medians animations', 'Animated demonstrations of median use and safety', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/medians-animations', 950, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0098', 'Animations', 'Estimation of safe passing time', 'Animated guidance on estimating safe passing time', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/passing-merging-and-sharing-the-road-animations', 960, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0099', 'Animations', 'Right of way animations', 'Animated scenarios demonstrating right-of-way rules', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/right-of-way-animations', 970, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0100', 'Animations', 'Stopping positions animations', 'Animated guidance on correct stopping positions', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/stopping-positions-animations', 980, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
INSERT INTO training_topics (jurisdiction, source_code, category, topic_name, sgi_description, youtube_link, handbook_link, display_order, active) VALUES ('SGI', 'T0101', 'Animations', 'Right turns', 'Animated demonstrations of safe right-turn procedures', NULL, 'https://sgi.sk.ca/handbook/-/knowledge_base/drivers/turning-animations', 990, TRUE) ON CONFLICT (jurisdiction, source_code) DO NOTHING;
