package com.sroadtutor.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme - Solar Surge (Vibrant Orange & Teal)
val LightPrimary = Color(0xFFA03D00)
val LightOnPrimary = Color(0xFFFFFFFF)
val LightPrimaryContainer = Color(0xFFFFDBCE)
val LightOnPrimaryContainer = Color(0xFF350F00)
val LightSecondary = Color(0xFF765849)
val LightOnSecondary = Color(0xFFFFFFFF)
val LightSecondaryContainer = Color(0xFFFFDBCE)
val LightOnSecondaryContainer = Color(0xFF2B160B)
val LightTertiary = Color(0xFF006A60)
val LightOnTertiary = Color(0xFFFFFFFF)
val LightTertiaryContainer = Color(0xFF71F7E4)
val LightOnTertiaryContainer = Color(0xFF00201C)
val LightError = Color(0xFFBA1A1A)
val LightOnError = Color(0xFFFFFFFF)
val LightErrorContainer = Color(0xFFFFDAD6)
val LightOnErrorContainer = Color(0xFF410002)
val LightBackground = Color(0xFFFFFBFF)
val LightOnBackground = Color(0xFF201A18)
val LightSurface = Color(0xFFFFFBFF)
val LightOnSurface = Color(0xFF201A18)
val LightSurfaceVariant = Color(0xFFF4DED4)
val LightOnSurfaceVariant = Color(0xFF53433C)
val LightOutline = Color(0xFF85736B)

// Dark Theme - Solar Surge (Vibrant Orange & Teal)
val DarkPrimary = Color(0xFFFFB596)
val DarkOnPrimary = Color(0xFF561D00)
val DarkPrimaryContainer = Color(0xFF7C2E00)
val DarkOnPrimaryContainer = Color(0xFFFFDBCE)
val DarkSecondary = Color(0xFFE6BEAC)
val DarkOnSecondary = Color(0xFF432B1E)
val DarkSecondaryContainer = Color(0xFF5C4032)
val DarkOnSecondaryContainer = Color(0xFFFFDBCE)
val DarkTertiary = Color(0xFF53DBC9)
val DarkOnTertiary = Color(0xFF003731)
val DarkTertiaryContainer = Color(0xFF005047)
val DarkOnTertiaryContainer = Color(0xFF71F7E4)
val DarkError = Color(0xFFFFB4AB)
val DarkOnError = Color(0xFF690005)
val DarkErrorContainer = Color(0xFF93000A)
val DarkOnErrorContainer = Color(0xFFFFDAD6)
val DarkBackground = Color(0xFF201A18)
val DarkOnBackground = Color(0xFFEDE0DB)
val DarkSurface = Color(0xFF201A18)
val DarkOnSurface = Color(0xFFEDE0DB)
val DarkSurfaceVariant = Color(0xFF53433C)
val DarkOnSurfaceVariant = Color(0xFFD8C2B9)
val DarkOutline = Color(0xFFA08D85)
